# Generated by Django 4.1.7 on 2023-04-10 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('transf_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receip_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_account', to='bank.account')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_account', to='bank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('t_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tamount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tr_type', models.CharField(max_length=1)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('acc_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='a_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.profile'),
        ),
    ]
